<?php 
$quote = Mage::getModel('checkout/cart')->getQuote();
?>
<li class="stripe-new stripe-payments-elements">
	<div class="stripe-payment" id="<?php echo Mage::getSingleton("stripe_payments/paymentIntent")->create()->getClientSecret()?>"></div>
	<div id="<?php echo Mage::getSingleton("stripe_payments/paymentIntent")->loadFromCache($quote)->id?>"></div>
  <label for="card-number" id="card-details-label">
    <?php echo Mage::helper('payment')->__('Enter your card details:') ?>
  </label>
</li>
<li class="stripe-new stripe-payments-elements no-wrap">
  <div id="stripe-payments-card-number" class="stripe-elements-field">
    <!-- a Stripe Element will be inserted here. -->
  </div>
  <div class="stripe-payments-brand"><i class="pf pf-credit-card" id="stripe-payments-brand-icon"></i></div>
</li>
<li class="stripe-new stripe-payments-elements no-wrap">
  <div id="stripe-payments-card-expiry" class="stripe-elements-field">
    <!-- a Stripe Element will be inserted here. -->
  </div>
  <div id="stripe-payments-card-cvc" class="stripe-elements-field">
    <!-- a Stripe Element will be inserted here. -->
  </div>
</li>
<li class="stripe-new stripe-payments-elements">
  <div class="pci-dss-info-block">
    <svg xmlns="http://www.w3.org/2000/svg" width="1.4em" height="1.4em" viewBox="0 0 24 24" id="pci-svg">
      <path d="m18,8l-1,0l0,-2c0,-2.76 -2.24,-5 -5,-5s-5,2.24 -5,5l0,2l-1,0c-1.1,0 -2,0.9 -2,2l0,10c0,1.1 0.9,2 2,2l12,0c1.1,0 2,-0.9 2,-2l0,-10c0,-1.1 -0.9,-2 -2,-2zm-6,9c-1.1,0 -2,-0.9 -2,-2s0.9,-2 2,-2s2,0.9 2,2s-0.9,2 -2,2zm3.1,-9l-6.2,0l0,-2c0,-1.71 1.39,-3.1 3.1,-3.1c1.71,0 3.1,0.92125 3.1,2.84372l0,-0.78122l0,3.0375z"/>
    </svg>
    <div class="pci-dss-info-text">
      <?php echo $this->__('Your card details are protected using PCI DSS v3.2 security standards.'); ?>
    </div>
  </div>
</li>
<?php 
?>
<script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery(document).on('change', 'input[name^="billing"]', function() {
			var firstname = jQuery('input[name="billing[firstname]"]').val();
			var lastname = jQuery('input[name="billing[lastname]"]').val();
			var company = jQuery('input[name="billing[company]"]').val();
			var email = jQuery('input[name="billing[email]"]').val();
			var phone = jQuery('input[name="billing[telephone]"]').val();
			var address = jQuery('input[name="billing[street][]"]').val();
			var city = jQuery('input[name="billing[city]"]').val();
			jQuery.ajax({
				url: '/stripe/verification/savebilling/',
				data: {firstname: firstname, lastname: lastname, company: company, email: email, phone: phone, address: address, city: city},
				type: 'post',
			})
		});
	});
</script>