<?php
// The ID using the code on the UL is important - this is what Magento will use to hide and display the 
// Form with javascript - it should be set to display:none by default
?>
<?php 
	$_code = $this->getMethod()->getCode();
	$total = Mage::getModel('checkout/session')->getQuote()->getBaseGrandTotal();
?>
<script>
	var affirm = document.getElementById('p_method_llapgoch_pay');
	if (affirm.checked) {
		new Ajax.Request(
				'/basicpayment/index/', {
						method: 'post',
						onComplete: function (response)
						{
								console.log('hi');
						}
				}
		);
	}
</script>
